# C1 W2 - Solving SLEs w/ numpy.linalg sub-library

<u>**Goal**</u>:

- Use `numpy.linalg` package to find the **solutions** to SLEs and evaluate the **determinant** of matrices.
- Explore the `numpy.linalg` sub-library to get to know its **properties**.

In [1]:
import numpy as np

<a name='1'></a>
## 1 - Representing and Solving a System of Linear Equations using Matrices

<a name='1.1'></a>
### 1.1 - Representing/ Solving SLEs using Matrices/NumPy

$$\begin{cases} 
4x_1-3x_2+x_3=-10, \\ 2x_1+x_2+3x_3=0, \\ -x_1+2x_2-5x_3=17, \end{cases}\tag{1}$$

Represent and solvelinear system $(1)$ using `NumPy`. 
- Let $A$ = coefficient matrix.
    + Each row = one equation, each column corresponds to the variable $x_1$, $x_2$, $x_3$.
- $b$ = 1-D array of the free (right side) coefficients:

In [2]:
A = np.array([
        [4, -3, 1],
        [2, 1, 3],
        [-1, 2, -5]
    ], dtype=np.dtype(float))

b = np.array([-10, 0, 17], dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nArray b:")
print(b)

Matrix A:
[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]

Array b:
[-10.   0.  17.]


Check the <u>dimensions</u> of $A$ and $b$ using `shape()` function.
Use **`np.linalg.solve(A, b)`** function to find the solution of the system $(1)$.
- The result will be saved in the 1-D array $x$ (elements will correspond to the values of $x_1$, $x_2$ and $x_3$).

In [3]:
# Check the dimensions of A and b
print(f"Shape of A: {np.shape(A)}")
print(f"Shape of b: {np.shape(b)}")
# Solve the system
x = np.linalg.solve(A, b)
print(f"Solution: {x}")

Shape of A: (3, 3)
Shape of b: (3,)
Solution: [ 1.  4. -2.]


<a name='1.2'></a>
### 1.2 - Evaluating determinant of a matrix

From previous example, Matrix $A$ = **square matrix**.
We can calculate its <u>**determinant**</u> using `np.linalg.det(A)` function:

In [4]:
d = np.linalg.det(A)
print(f"Determinant of matrix A: {d:.2f}")

Determinant of matrix A: -60.00


<a name='1.3'></a>
### 1.3 - Handling contradictory/inconsistent (singular) matrix and LinAlgError

Using `np.linalg.solve` to solve an inconsistent system (no solution) produces **LinAlgError**.

Given another system of linear equations:

$$\begin{cases} 
x_1+x_2+x_3=2, \\ x_2-3x_3=1, \\ 2x_1+x_2+5x_3=0, \end{cases}\tag{2}$$

Attempting to find determinant gives the error. Therefore, you will need to <u>check for this edge case</u>, and do **error/exception handling** using <u>*try/except blocks*</u> to prevent your program from crashing.

In [6]:
A_2= np.array([
        [1, 1, 1],
        [0, 1, -3],
        [2, 1, 5]
    ], dtype=np.dtype(float))

b_2 = np.array([2, 1, 0], dtype=np.dtype(float))

try:
    print(np.linalg.solve(A_2, b_2))
except np.linalg.LinAlgError as e:
    print(f"LinAlgError: {e}")

LinAlgError: Singular matrix
