In [8]:
%load_ext autoreload
%autoreload 2

import sys
from pathlib import Path

project_root = Path.cwd().parent
sys.path.insert(0, str(project_root))

from utils.matrices import MyMatrixSolver
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [9]:
input_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [10]:
matrix_solver = MyMatrixSolver(input_array)
matrix_solver.summary()

 Matrix has             RREF: [[ 1.  0. -1.]
 [ 0.  1.  2.]
 [ 0.  0.  0.]]             Dimensions: (3, 3)             Rank: None             Trace: None             Eigenvalues: None             Eigenvectors: None             Null Space: None             Column Space: None             Row Space: None             Basis: None             Kernel: None             Orthonormal Basis: None             Covariance Matrix: None             Correlation Matrix: None             Principal Components: None             Principal Component Analysis: None             Singular Value Decomposition: None         


In [11]:
result_truncated = matrix_solver._truncate_matrix(input_array, 1)

In [12]:
result_truncated

array([[4, 6],
       [7, 9]])

In [13]:
matrix_solver.determinant

np.int64(0)

In [14]:
input_array_2 = np.array([[ 0,  1,  0, -2,  1],
       [ 1,  0,  3,  1,  1],
       [ 1, -1,  1,  1,  1],
       [ 2,  2,  1,  0,  1],
       [ 3,  1,  1,  1,  2]])
matrix_solver_2  = MyMatrixSolver(input_array_2)

In [72]:
input_array_2

array([[ 0,  1,  0, -2,  1],
       [ 1,  0,  3,  1,  1],
       [ 1, -1,  1,  1,  1],
       [ 2,  2,  1,  0,  1],
       [ 3,  1,  1,  1,  2]])